package Exceptions.Aufgabe7;

public class Fehler {

	public static void main(String[] args) {
		try {
			System.out.println("try");
		} finally {
			System.out.println("finally");
		}
	}

}
